// Generated by CoffeeScript 1.9.3
(function() {
  $(function() {
    return $(document).on("click", "#do_products", function() {
      return alert('uhum');
    });
  });

  $(function() {
    var all;
    window.ruid = "G" + (Number(localStorage.getItem('lastRUID') || 0) + 1);
    $('#RUID').html(window.ruid);
    localStorage.setItem('lastRUID', window.ruid);
    console.log(window.ruid);
    all = localStorage.getObject('allOpenGraphs');
    all[window.ruid] = uuid;
    localStorage.setObject('allOpenGraphs', all);
    return window.onbeforeunload = function() {
      all = localStorage.getObject('allOpenGraphs');
      delete all[window.ruid];
      localStorage.setObject('allOpenGraphs', all);
      if (Object.keys(localStorage.getObject('allOpenGraphs')).length === 0) {
        return localStorage.setItem('lastRUID', 0);
      }
    };
  });

  Storage.prototype.setObject = function(key, value) {
    return this.setItem(key, JSON.stringify(value));
  };

  Storage.prototype.getObject = function(key) {
    var value;
    value = this.getItem(key);
    return value && JSON.parse(this.getItem(key));
  };

}).call(this);

//# sourceMappingURL=panda.js.map
